//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.25 at 05:35:33 PM GMT 
//


package com.github.ronanquillevre.jqassistantrulesjava;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for executableRuleType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="executableRuleType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.buschmais.com/jqassistant/core/analysis/rules/schema/v1.0}referenceableType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="requiresConcept" type="{http://www.buschmais.com/jqassistant/core/analysis/rules/schema/v1.0}referenceType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="deprecated" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;choice&gt;
 *           &lt;element name="cypher" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *           &lt;element name="useTemplate" type="{http://www.buschmais.com/jqassistant/core/analysis/rules/schema/v1.0}referenceType"/&gt;
 *           &lt;element name="script" type="{http://www.buschmais.com/jqassistant/core/analysis/rules/schema/v1.0}scriptType"/&gt;
 *         &lt;/choice&gt;
 *         &lt;element name="parameter" type="{http://www.buschmais.com/jqassistant/core/analysis/rules/schema/v1.0}parameterType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="verify" type="{http://www.buschmais.com/jqassistant/core/analysis/rules/schema/v1.0}verificationType" minOccurs="0"/&gt;
 *         &lt;element name="report" type="{http://www.buschmais.com/jqassistant/core/analysis/rules/schema/v1.0}reportType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="severity" type="{http://www.buschmais.com/jqassistant/core/analysis/rules/schema/v1.0}severityEnumType" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "executableRuleType", propOrder = {
    "requiresConcept",
    "description",
    "deprecated",
    "cypher",
    "useTemplate",
    "script",
    "parameter",
    "verify",
    "report"
})
@XmlSeeAlso({
    TemplateType.class,
    ConceptType.class,
    ConstraintType.class
})
public abstract class ExecutableRuleType
    extends ReferenceableType
{

    protected List<ReferenceType> requiresConcept;
    protected String description;
    protected String deprecated;
    protected String cypher;
    protected ReferenceType useTemplate;
    protected ScriptType script;
    protected List<ParameterType> parameter;
    protected VerificationType verify;
    protected ReportType report;
    @XmlAttribute(name = "severity")
    protected SeverityEnumType severity;

    /**
     * Gets the value of the requiresConcept property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the requiresConcept property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRequiresConcept().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReferenceType }
     * 
     * 
     */
    public List<ReferenceType> getRequiresConcept() {
        if (requiresConcept == null) {
            requiresConcept = new ArrayList<ReferenceType>();
        }
        return this.requiresConcept;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the deprecated property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeprecated() {
        return deprecated;
    }

    /**
     * Sets the value of the deprecated property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeprecated(String value) {
        this.deprecated = value;
    }

    /**
     * Gets the value of the cypher property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCypher() {
        return cypher;
    }

    /**
     * Sets the value of the cypher property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCypher(String value) {
        this.cypher = value;
    }

    /**
     * Gets the value of the useTemplate property.
     * 
     * @return
     *     possible object is
     *     {@link ReferenceType }
     *     
     */
    public ReferenceType getUseTemplate() {
        return useTemplate;
    }

    /**
     * Sets the value of the useTemplate property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferenceType }
     *     
     */
    public void setUseTemplate(ReferenceType value) {
        this.useTemplate = value;
    }

    /**
     * Gets the value of the script property.
     * 
     * @return
     *     possible object is
     *     {@link ScriptType }
     *     
     */
    public ScriptType getScript() {
        return script;
    }

    /**
     * Sets the value of the script property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScriptType }
     *     
     */
    public void setScript(ScriptType value) {
        this.script = value;
    }

    /**
     * Gets the value of the parameter property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the parameter property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getParameter().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ParameterType }
     * 
     * 
     */
    public List<ParameterType> getParameter() {
        if (parameter == null) {
            parameter = new ArrayList<ParameterType>();
        }
        return this.parameter;
    }

    /**
     * Gets the value of the verify property.
     * 
     * @return
     *     possible object is
     *     {@link VerificationType }
     *     
     */
    public VerificationType getVerify() {
        return verify;
    }

    /**
     * Sets the value of the verify property.
     * 
     * @param value
     *     allowed object is
     *     {@link VerificationType }
     *     
     */
    public void setVerify(VerificationType value) {
        this.verify = value;
    }

    /**
     * Gets the value of the report property.
     * 
     * @return
     *     possible object is
     *     {@link ReportType }
     *     
     */
    public ReportType getReport() {
        return report;
    }

    /**
     * Sets the value of the report property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReportType }
     *     
     */
    public void setReport(ReportType value) {
        this.report = value;
    }

    /**
     * Gets the value of the severity property.
     * 
     * @return
     *     possible object is
     *     {@link SeverityEnumType }
     *     
     */
    public SeverityEnumType getSeverity() {
        return severity;
    }

    /**
     * Sets the value of the severity property.
     * 
     * @param value
     *     allowed object is
     *     {@link SeverityEnumType }
     *     
     */
    public void setSeverity(SeverityEnumType value) {
        this.severity = value;
    }

}
