//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.25 at 05:35:33 PM GMT 
//


package com.github.ronanquillevre.jqassistantrulesjava;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *         &lt;element name="template" type="{http://www.buschmais.com/jqassistant/core/analysis/rules/schema/v1.0}templateType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="concept" type="{http://www.buschmais.com/jqassistant/core/analysis/rules/schema/v1.0}conceptType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="constraint" type="{http://www.buschmais.com/jqassistant/core/analysis/rules/schema/v1.0}constraintType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="group" type="{http://www.buschmais.com/jqassistant/core/analysis/rules/schema/v1.0}groupType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="metricGroup" type="{http://www.buschmais.com/jqassistant/core/analysis/rules/schema/v1.0}metricGroupType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "templateOrConceptOrConstraint"
})
@XmlRootElement(name = "jqassistant-rules")
public class JqassistantRules {

    @XmlElements({
        @XmlElement(name = "template", type = TemplateType.class),
        @XmlElement(name = "concept", type = ConceptType.class),
        @XmlElement(name = "constraint", type = ConstraintType.class),
        @XmlElement(name = "group", type = GroupType.class),
        @XmlElement(name = "metricGroup", type = MetricGroupType.class)
    })
    protected List<ReferenceableType> templateOrConceptOrConstraint;

    /**
     * Gets the value of the templateOrConceptOrConstraint property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the templateOrConceptOrConstraint property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTemplateOrConceptOrConstraint().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TemplateType }
     * {@link ConceptType }
     * {@link ConstraintType }
     * {@link GroupType }
     * {@link MetricGroupType }
     * 
     * 
     */
    public List<ReferenceableType> getTemplateOrConceptOrConstraint() {
        if (templateOrConceptOrConstraint == null) {
            templateOrConceptOrConstraint = new ArrayList<ReferenceableType>();
        }
        return this.templateOrConceptOrConstraint;
    }

}
