//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.25 at 05:35:33 PM GMT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.buschmais.com/jqassistant/core/analysis/rules/schema/v1.0")
package com.github.ronanquillevre.jqassistantrulesjava;
