//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.25 at 05:35:33 PM GMT 
//


package com.github.ronanquillevre.jqassistantrulesjava;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for severityEnumType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="severityEnumType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="blocker"/&gt;
 *     &lt;enumeration value="critical"/&gt;
 *     &lt;enumeration value="major"/&gt;
 *     &lt;enumeration value="minor"/&gt;
 *     &lt;enumeration value="info"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "severityEnumType")
@XmlEnum
public enum SeverityEnumType {

    @XmlEnumValue("blocker")
    BLOCKER("blocker"),
    @XmlEnumValue("critical")
    CRITICAL("critical"),
    @XmlEnumValue("major")
    MAJOR("major"),
    @XmlEnumValue("minor")
    MINOR("minor"),
    @XmlEnumValue("info")
    INFO("info");
    private final String value;

    SeverityEnumType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SeverityEnumType fromValue(String v) {
        for (SeverityEnumType c: SeverityEnumType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
